version: '3.8'

services:
  router-api:
    build:
      context: ..
      dockerfile: router-api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      - ../.logs:/app/.logs
      - ../llm_router:/app/llm_router:ro
      - ../sources:/app/sources:ro
      - ../prompts:/app/prompts:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - router-network

networks:
  router-network:
    driver: bridge 